test:
  video_dir: ~/samples/nba50
  num_paths: 20
  prefix_length: 30
  max_length: 20
  num_id_to_upload: 0
  num_paths_to_upload: 3
  temperature: 1.0
  compute_multiple_of_5frames: true
  feet2metre: true
  save_dir: ~/samples/nba50/test_samples
  save_only: false
  num_id_to_save: 128