# Minimal, fast debug run on CPU
wandb:
  project: relativetransformer-nfl
  name: relativetransformer-combinedscenes-mog-nodecoder
train:
  seed: 0
  validate_at_start: true
  test: false
  ckpt: null
  results_dir: ~/ckpt
  monitor_metric: jade_min

# Lightning Trainer
trainer:
  accelerator: gpu
  devices: 1
  precision: 32-true
  max_epochs: 300
  fast_dev_run: false           # one batch train/val/test and exit
  limit_train_batches: null       # safety; only a couple batches
  limit_val_batches: null
  limit_test_batches: null
  log_every_n_steps: 1
  enable_checkpointing: true
  gradient_clip_val: 1.0
  gradient_clip_algorithm: norm
  check_val_every_n_epoch: 5
  
interface:
  name: AutoregressiveMultiplePathPredictionInterface
  diff_as_target: true
  diff_in_input: true
  data_mean: [60.0, 26.5]
  data_std: [30.0, 13.25] # we get the data to the range of -2.0 to 2.0
  diff_mean: [0.0, 0.0]
  diff_std: [1.0, 1.0]
  # diff_std: [21.0, 6.0] # we get the data to the range of -2.0 to 2.0
  game: football
  validation_prefix_length: 30
  validation_max_length: 20
  validation_num_paths: 8
  num_id_to_upload: 3
  num_paths_to_upload: 3
  upload_every_n_epochs: 10
  masking_ratio_start: 0.00
  masking_ratio_end: 0.00
  masking_end_at_training_pct: 0.1
  entropy_weight: 0.05
  min_std: 0.01

dataset:
  name: TrajectoryDataModule
  train_bsz: 192
  val_bsz: 512
  train_size: null
  val_size: 2560
  num_workers: 0
  data_dir: ~/data/traj/nfl

# Small model for speed (used by CPU class after the code tweak below)
model:
  name: RelativeTransformer
  args:
    num_relative_transformer_blocks: 0
    relative_transformer_block_config:
      d_model: 128
      d_mesh: 260
      n_head: 8
      d_ff: 256
      dropout: 0.1
      use_pffn: true
      ln_before_ffn: true
    motion_transformer_encoder_config:
      pointnet_in_channels: 4
      pointnet_hidden_dim: 64
      pointnet_num_layers: 3
      pointnet_num_pre_layers: 1
      pointnet_out_channels: 64
      entity_embedding_dim: 64
      d_model: 128
      use_pre_norm: true
      num_attn_layers: 8
      num_attn_heads: 8
      team_size: 11
    d_agentwise_mlp: [48]
    d_shared_head_mlp: 1024
    num_scenes: 8
    num_agents: 23
    traj_conditioning: true
    d_traj: 4
    dropout: 0.0

# Optimizer
optimizer:
  lr: 0.002
  weight_decay: 0.01
  lr_schedule:
    div_factor: 15
    final_div_factor: 200
    pct_start: 0.1
    total_steps: null
