test:
  video_dir: ~/samples/nfl
  num_paths: 20
  prefix_length: 30
  max_length: 20
  num_id_to_upload: 0
  num_paths_to_upload: 5
  temperature: 1.0
  num_id_to_save: 0
  compute_multiple_of_5frames: true